---
- hosts: base_cloud
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Install docker
    apt:
      name: docker.io
      state: present

  - name: Add cloud user to docker group
    user:
      name: "{{ username }}"
      group: docker

  - name: Restart docker service
    command: systemctl restart docker

  - name: Create containerd directory
    file:
      path: /etc/containerd
      state: directory

  - name: Copy containerd config from local to target
    copy: 
      src: ~/.continuum/config.toml
      dest: /etc/containerd/config.toml

  - name: Replace registry ip in containerd config file
    command: sed -i 's/REGISTRY-IP/{{ registry_ip }}/g' /etc/containerd/config.toml

  - name: Restart containerd service
    command: systemctl restart containerd

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Enable ipv4 forwarding
    shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
  
  - name: Reload ip settings
    command: sysctl -p

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  # Use this version with KubeEdge 1.6.1
  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
        - kubelet=1.24.7-00
        - kubeadm=1.24.7-00
        - kubectl=1.24.7-00

  - name: Get Calico
    get_url:
      url: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      dest: "/"
      mode: '0755'

  - name: Install Mosquitto
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
        - mosquitto=1.6.9-1

  - name: Update SSH settings to allow many parallel sessions
    blockinfile:
      path: /etc/ssh/sshd_config
      block: |
        MaxSessions 10000
        MaxStartups 10000

  - name: Reset SSH client
    command: systemctl restart sshd